apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: platformapi
spec:
  replicas: 1
  selector:
    matchLabels:
      service: platformapi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: platformapi
    spec:
      containers:
      - name: platformapi
        image: {{ printf "%s" (pluck .Values.global.env .Values.IMAGE | first | default .Values.IMAGE._default) }}
        imagePullPolicy: Always
        env:
        - name: NP_K8S_API_URL
          value: http://localhost:8001
        - name: NP_K8S_AUTH_TYPE
          value: none
        - name: NP_STORAGE_TYPE
          value: nfs
        - name: NP_STORAGE_NFS_SERVER
          value: "{{ printf "%s" (pluck .Values.global.env .Values.NP_STORAGE_NFS_SERVER | first | default .Values.NP_STORAGE_NFS_SERVER._default) }}"
        - name: NP_STORAGE_NFS_PATH
          value: /nfs
        - name: NP_STORAGE_HOST_MOUNT_PATH
          value: /nfs
        - name: NP_K8S_JOBS_INGRESS_NAME
          value: platformjobsingress
        - name: NP_K8S_JOBS_INGRESS_DOMAIN_NAME
          value: "{{ printf "%s" (pluck .Values.global.env .Values.NP_K8S_JOBS_INGRESS_DOMAIN_NAME | first | default .Values.NP_K8S_JOBS_INGRESS_DOMAIN_NAME._default) }}"
        - name: NP_DB_REDIS_URI
          value: "{{ printf "%s" (pluck .Values.global.env .Values.NP_DB_REDIS_URI | first | default .Values.NP_DB_REDIS_URI._default) }}"
      - name: kubeproxy
        image: lachlanevenson/k8s-kubectl:v1.10.3
        args: [proxy]
---
apiVersion: v1
kind: Service
metadata:
  name: platformapi
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    service: platformapi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: platformapi-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefix
spec:
  rules:
  - host: {{ printf "%s" (pluck .Values.global.env .Values.INGRESS_HOST | first | default .Values.INGRESS_HOST._default) }}
    http:
      paths:
      - path: /api/v1/storage
        backend:
          serviceName: platformstorageapi
          servicePort: 8080
      - path: /api/v1/users
        backend:
          serviceName: platformauthapi
          servicePort: 8080
      - path: /api/v1
        backend:
          serviceName: platformapi
          servicePort: 8080
