FROM python:3.7.2-stretch

WORKDIR /neuromation

ARG PIP_EXTRA_INDEX_URL

# installing dependencies ONLY
COPY setup.py ./
RUN \
    pip install -e . && \
    pip uninstall -y platform-api

# installing platform-api
COPY alembic.ini alembic.ini
COPY alembic alembic
COPY platform_api platform_api
RUN pip install -e .

ENV NP_API_PORT=8080
EXPOSE $NP_API_PORT

CMD platform-api
