[build-system]
requires = [
    "setuptools>=45",
    "wheel",
    "setuptools_scm>=6.2",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
git_describe_command = "git describe --dirty --tags --long --match v*.*.*"

[tool.black]
exclude = '''
/(
      \.git
    | venv
    | __pycache__
)/
'''
