apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ssh
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ssh
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: ssh
    spec:
      containers:
      - name: ssh
        image: {{ printf "%s" (pluck .Values.global.env .Values.IMAGE | first | default .Values.IMAGE._default) }}
        command: TODO
        imagePullPolicy: Always
        env:
        - name: NP_K8S_API_URL
          value: http://localhost:8001
        - name: NP_K8S_AUTH_TYPE
          value: none
        - name: NP_STORAGE_TYPE
          value: nfs
        - name: NP_STORAGE_NFS_SERVER
          value: "{{ printf "%s" (pluck .Values.global.env .Values.NP_STORAGE_NFS_SERVER | first | default .Values.NP_STORAGE_NFS_SERVER._default) }}"
        - name: NP_STORAGE_NFS_PATH
          value: "{{ printf "%s" (pluck .Values.global.env .Values.NP_STORAGE_NFS_PATH | first | default .Values.NP_STORAGE_NFS_PATH._default) }}"
        - name: NP_STORAGE_HOST_MOUNT_PATH
          value: "{{ printf "%s" (pluck .Values.global.env .Values.NP_STORAGE_NFS_PATH | first | default .Values.NP_STORAGE_NFS_PATH._default) }}"
        - name: NP_K8S_JOBS_INGRESS_NAME
          value: platformjobsingress
        - name: NP_K8S_JOBS_INGRESS_DOMAIN_NAME
          value: "{{ printf "%s" (pluck .Values.global.env .Values.NP_K8S_JOBS_INGRESS_DOMAIN_NAME | first | default .Values.NP_K8S_JOBS_INGRESS_DOMAIN_NAME._default) }}"
        - name: NP_K8S_SSH_INGRESS_DOMAIN_NAME
          value: "{{ printf "%s" (pluck .Values.global.env .Values.NP_K8S_SSH_INGRESS_DOMAIN_NAME | first | default .Values.NP_K8S_SSH_INGRESS_DOMAIN_NAME._default) }}"
        - name: NP_DB_REDIS_URI
          value: "{{ printf "%s" (pluck .Values.global.env .Values.NP_DB_REDIS_URI | first | default .Values.NP_DB_REDIS_URI._default) }}"
        - name: NP_AUTH_URL
          value: http://platformauthapi:8080
        - name: NP_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: platformservices-secret
              key: compute_token
        - name: NP_REGISTRY_HOST
          value: "{{ printf "%s" (pluck .Values.global.env .Values.NP_REGISTRY_HOST | first | default .Values.NP_REGISTRY_HOST._default) }}"
        - name: NP_K8S_NODE_LABEL_GPU
          value: cloud.google.com/gke-accelerator
        - name: NP_GKE_GPU_MODELS
          value: "{{ printf "%s" (pluck .Values.global.env .Values.NP_GKE_GPU_MODELS | first | default .Values.NP_GKE_GPU_MODELS._default) }}"
        - name: NP_K8S_NODE_LABEL_PREEMPTIBLE
          value: cloud.google.com/gke-preemptible
      - name: kubeproxy
        image: lachlanevenson/k8s-kubectl:v1.10.3
        args: [proxy]
---
apiVersion: v1
kind: Service
metadata:
  name: ssh
spec:
  type: "LoadBalancer"
  ports:
  - port: 22
    targetPort: 22
  selector:
    service: ssh
