{{- if eq .Values.global.env "dev" }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev2-volume
  labels:
    failure-domain.beta.kubernetes.io/zone: us-central1-a__us-central1-c
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: {{ printf "%s" (pluck .Values.global.env .Values.VOLUME | first | default .Values.VOLUME._default) }}
    fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dev2-volume-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
{{- end }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jumphost
spec:
  replicas: 1
  selector:
    matchLabels:
      service: jumphost
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: jumphost
    spec:
      volumes:
      - name: dev2-volume
        {{- if eq .Values.global.env "dev" }}
        persistentVolumeClaim:
          claimName: dev2-volume-pvc
        {{ else }}
        gcePersistentDisk:
          pdName: {{ printf "%s" (pluck .Values.global.env .Values.VOLUME | first | default .Values.VOLUME._default) }}
          fsType: ext4
          {{- end }}
      containers:
      - name: jumphost
        image: {{ printf "%s" (pluck .Values.global.env .Values.IMAGE | first | default .Values.IMAGE._default) }}
        imagePullPolicy: Always
        ports:
          - containerPort: 22
        volumeMounts:
        - name: dev2-volume
          mountPath: /home
        env:
        - name: NP_JUMP_HOST_ROOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: jumphost-secret
              key: authorizedkeys
---
apiVersion: v1
kind: Service
metadata:
  name: jumphost
spec:
  type: "LoadBalancer"
  ports:
  - port: 22
    targetPort: 22
  selector:
    service: jumphost