NP_CLUSTER_NAME: default
NP_PLATFORM_API_URL: https://dev.neu.ro/api/v1
NP_ADMIN_URL: https://dev.neu.ro/apis/admin/v1
NP_AUTH_PUBLIC_URL: https://dev.neu.ro/api/v1/users
NP_JOBS_INGRESS_OAUTH_AUTHORIZE_URL: https://dev.neu.ro/oauth/authorize
NP_SENTRY_URL: "https://11316dd021994d7085c50e86c2ae404c@o454648.ingest.sentry.io/5597106"
NP_SENTRY_CLUSTER: "dev-azure"

platform:
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: compute_token

ingress:
  enabled: true

  extraAnnotations:
    external-dns.platform.neuromation.io: "true"
  hosts: [dev.neu.ro]
