platform:
  authUrl: http://platformauthapi:8080
  configUrl: http://platformconfig:8080/api/v1
  adminUrl: http://platformadmin:8080/apis/admin/v1
  apiUrl: http://platformapi:8080/api/v1
  registryUrl: https://registry-dev.neu.ro
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: compute_token

jobs:
  priorityClassName: platform-job
  ingressOAuthAuthorizeUrl: https://dev.neu.ro/oauth/authorize

storages:
- type: pvc
  claimName: pvc-platform-storage-jobs

ingress:
  enabled: true

  extraAnnotations:
    external-dns.platform.neuromation.io: "true"
  hosts: [dev.neu.ro]

sentry:
  dsn: https://432bc48cd2444be7afec5efeb1fc03a6@o489136.ingest.sentry.io/5530426
  clusterName: dev
  sampleRate: 0.002
