version: 2
jobs:

  test:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    working_directory: ~/.go_workspace/src/github.com/neuromation/platform-api
    steps:
      - checkout
      - run:
          name: Running API tests
          command: |
            make up;
            make run_api_tests;
            make down;
      - run:
          name: Running backend integration tests
          command: |
            make up;
            make integration_test;
            make down;
      - run:
          name: code coverage
          command: |
            make test_coverage;
            bash <(curl -s https://codecov.io/bash);
  test-docker:
    docker:
      - image: circleci/golang:1.10
      - image: mesoscloud/zookeeper:3.4.6-centos-7
      - image: mesosphere/mesos-master:1.4.1
    working_directory: /go/src/github.com/neuromation/platform-api
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: code coverage
          command: |
            make test_coverage;
            bash <(curl -s https://codecov.io/bash);
workflows:
  version: 2

  main:
    jobs:
      - test
      - test-docker
