defaults: &defaults
  machine:
    image: circleci/classic:201711-01
    docker_layer_caching: true
  working_directory: ~/.go_workspace/src/github.com/neuromation/platform-api


version: 2
jobs:

  test:
    <<: *defaults
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: |
          mkdir -p $TEST_RESULTS/junit
          go get github.com/jstemmer/go-junit-report
      - run:
          name: Running unit and integration tests
          command: |
            make up
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/junit/go-test-report.xml" EXIT
            make go_integration_test | tee ${TEST_RESULTS}/go-test.out;
            bash <(curl -s https://codecov.io/bash);
      - run:
          name: cleanup
          command: |
            make down
            make up
      - run:
          name: Running API tests
          command: make ci_run_api_tests

      - store_test_results:
          path: /tmp/test-results

  gke_deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: GKE Auth
          command: |
            make -s gke_login

      - run:
          name: GKE Docker Push
          command: |
            make gke_docker_push

      - run:
          name: GKE K8s Deploy
          command: |
            make gke_k8s_deploy
  k8s:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo bash -c "yes | add-apt-repository ppa:jonathonf/python-3.6 && apt-get update && apt-get install -y python3.6"
            sudo apt-get install nfs-common
      - run:
          name: Running Kubernetes
          command: |
            make start_k8s

      - run:
          name: Testing Kubernetes
          command: |
            make test_k8s

      - run:
          name: Run Platform Tests
          command: |
            make test_k8s_platform_api

      - run:
          name: Running E2E Test Suite
          command: |
            make test_k8s_platform_api_e2e

      - run:
          name: Stopping Kubernetes
          command: |
            make clean_k8s
          when: always


workflows:
  version: 2

  main:
    jobs:
      - k8s:
          context: org-global
      - test:
          context: org-global
      - gke_deploy:
          context: org-global
          requires:
            - k8s          
            - test
          filters:
            branches:
              only:
                - master
