defaults: &defaults
  machine:
    image: circleci/classic:201711-01
    docker_layer_caching: true
  working_directory: ~/platform-api


version: 2
jobs:

  gke_dev_deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: GKE Auth
          command: |
            make -s gke_login

      - run:
          name: GKE Docker Push
          command: |
            make gke_docker_push

      - run:
          name: GKE K8s Deploy
          command: |
            make gke_k8s_deploy_dev

  gke_stage_deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: GKE Auth
          command: |
            make -s gke_login

      - run:
          name: GKE Docker Push
          command: |
            make gke_docker_push

      - run:
          name: GKE K8s Deploy
          command: |
            make gke_k8s_deploy_staging

  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            # NOTE: python3.6-dev is required to compile Hiredis
            sudo bash -c "yes | add-apt-repository ppa:jonathonf/python-3.6 && apt-get update && apt-get install -y python3.6-dev"
            sudo apt-get install nfs-common
      - run:
          name: Running Kubernetes
          command: |
            make start_k8s

      - run:
          name: Testing Kubernetes
          command: |
            make test_k8s

      - run:
          name: Run Platform Tests
          command: |
            make test_k8s_platform_api

      - run:
          name: Running E2E Test Suite
          command: |
            make test_k8s_platform_api_e2e

      - run:
          name: Stopping Kubernetes
          command: |
            make clean_k8s
          when: always


workflows:
  version: 2

  main:
    jobs:
      - test:
          context: org-global
      - gke_dev_deploy:
          context: org-global
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - gke_stage_deploy:
          context: org-global
          requires:
            - test
          filters:
            branches:
              only:
                - /release.*/
