version: 2
jobs:

  test:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    working_directory: ~/.go_workspace/src/github.com/neuromation/platform-api
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: Running API tests
          command: |
            make up;
            make run_api_tests;
            make down;
      - run:
          name: Running backend integration tests
          command: |
            make up;
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make integration_test | tee ${TEST_RESULTS}/go-test.out;
            make down;

      - store_test_results:
        path: /tmp/test-results

workflows:
  version: 2

  main:
    jobs:
      - test
