version: 2
jobs:

  test:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    working_directory: ~/.go_workspace/src/github.com/neuromation/platform-api
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: |
          mkdir -p $TEST_RESULTS/junit
          go get github.com/jstemmer/go-junit-report
          make up
      - run:
          name: Running API tests
          command: make ci_run_api_tests
      - run:
          name: cleanup
          command: |
            make down
            make up
      - run:
          name: Running unit and integration tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/junit/go-test-report.xml" EXIT
            make go_test_with_coverage | tee ${TEST_RESULTS}/go-test.out;

      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2

  main:
    jobs:
      - test:
          context: org-global
