version: 2
jobs:

  test:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    working_directory: ~/.go_workspace/src/github.com/neuromation/platform-api
    steps:
      - checkout
      - run:
          name: Running API tests
          command: |
            make up;
            make run_api_tests;
            make down;
      - run:
          name: Running backend integration tests with coverage
          command: |
            make up;
            make test_with_coverage;
            bash <(curl -s https://codecov.io/bash);
            make down;

workflows:
  version: 2

  main:
    jobs:
      - test
