version: 2
jobs:

  test:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    working_directory: ~/.go_workspace/src/github.com/neuromation/platform-api
    steps:
      - checkout
      - run:
          name: Running backend integration tests
          command: |
            make up;
            make integration_test;
            make down;
      - run:
          name: Running API tests
          command: |
            make up;
            make run_api_tests;
            make down;

workflows:
  version: 2

  main:
    jobs:
      - test:
          context: org-global
