defaults: &defaults
  machine:
    image: circleci/classic:201711-01
    docker_layer_caching: true
  working_directory: ~/.go_workspace/src/github.com/neuromation/platform-api


version: 2
jobs:

  test:
    <<: *defaults
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: |
          mkdir -p $TEST_RESULTS/junit
          go get github.com/jstemmer/go-junit-report
      - run:
          name: Running unit and integration tests
          command: |
            make up
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/junit/go-test-report.xml" EXIT
            make go_integration_test | tee ${TEST_RESULTS}/go-test.out;
            bash <(curl -s https://codecov.io/bash);
      - run:
          name: cleanup
          command: |
            make down
            make up
      - run:
          name: Running API tests
          command: make ci_run_api_tests

      - store_test_results:
          path: /tmp/test-results

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Building and pushing docker images
          command: |
            make build_api push_api

      - run:
          name: Deploying on dev environment
          command: |
              make deploy_platformapi_dev

workflows:
  version: 2

  main:
    jobs:
      - test:
          context: org-global
      - deploy:
          context: org-global
          requires:
            - test
          filters:
            branches:
              only:
                - master
