version: 2
jobs:

  test:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    working_directory: /usr/local/go/src/github.com/neuromation/platform-api
    steps:
      - checkout
      - run:
          name: Running API tests
          command: |
            make run_api_tests
      - run:
          name: Running backend tests
          command: |
            make integration_test

workflows:
  version: 2

  main:
    jobs:
      - test
