defaults: &defaults
  machine:
    image: circleci/classic:201711-01
    docker_layer_caching: true
  working_directory: ~/platform-api


version: 2
jobs:

  gke_dev_deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: GKE Auth
          command: |
            make -s gke_login

      - run:
          name: GKE Docker Push
          command: |
            make gke_docker_push

      - run:
          name: GKE K8s Deploy
          command: |
            make gke_k8s_deploy_dev

  gke_stage_deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: GKE Auth
          command: |
            make -s gke_login

      - run:
          name: GKE Docker Push
          command: |
            make gke_docker_push

      - run:
          name: GKE K8s Deploy
          command: |
            make gke_k8s_deploy_staging

  test:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Installing Dependencies
          command: |
            pyenv install --debug 3.6.3
            pyenv local 3.6.3-debug
            sudo apt-get update
            sudo apt-get install nfs-common

      - run:
          name: Running Kubernetes
          command: |
            make start_k8s

# below rule cleans out hiredis, this is due to circle ci issue, to be resolved by moving to dockerized test execution
      - run:
          name: Setting Up Python Virtual Environment
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -U pip
            make setup
            pip uninstall -y hiredis

      - run:
          name: Running Static Code Analysis
          command: |
            source venv/bin/activate
            make lint

      - run:
          name: Run Platform Tests
          command: |
            source venv/bin/activate
            make test_k8s_platform_api

      - run:
          name: Running E2E Test Suite
          command: |
            source venv/bin/activate
            make test_k8s_platform_api_e2e

      - run:
          name: Stopping Kubernetes
          command: |
            make clean_k8s
          when: always


workflows:
  version: 2

  main:
    jobs:
      - test:
          context: org-global
      - gke_dev_deploy:
          context: org-global
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - gke_stage_deploy:
          context: org-global
          requires:
            - test
          filters:
            branches:
              only:
                - /release.*/
            tags:  # TODO: eventually should be moved to a separate job
              only:
                - /release.*/
