{{- if .Values.ingress.enabled }}
{{- $ingressApiIsStable := eq (include "k8s.ingress.isStable" .) "true" -}}
{{- $ingressSupportsIngressClassName := eq (include "k8s.ingress.supportsIngressClassName" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "k8s.ingress.supportsPathType" .) "true" -}}
apiVersion: {{ include "k8s.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "platformApiPoller.fullname" . }}
  labels: {{ include "platformApiPoller.labels.standard" . | nindent 4 }}
    service: platform-api-poller
{{- with .Values.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4}}
{{- end }}
spec:
  {{- if and $ingressSupportsIngressClassName .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /api/v1/poller
        {{- if $ingressSupportsPathType }}
        pathType: Prefix
        {{- end }}
        backend:
          {{- if $ingressApiIsStable }}
          service:
            name: {{ include "platformApiPoller.fullname" $ }}
            port:
              name: http
          {{- else }}
          serviceName: {{ include "platformApiPoller.fullname" $ }}
          servicePort: http
          {{- end }}
  {{- end }}
{{- end }}
