apiVersion: v1
kind: Service
metadata:
  name: {{ include "platformApiPoller.fullname" . }}
  labels: {{ include "platformApiPoller.labels.standard" . | nindent 4 }}
    service: platform-api-poller
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: tcp-web
  selector:
    app: {{ include "platformApiPoller.name" . }}
    release: {{ .Release.Name }}
    service: platform-api-poller
