apiVersion: v1
kind: Service
metadata:
  name: {{ include "platformApiPoller.fullname" . }}
  labels:
    {{- include "platformApiPoller.labels.standard" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: tcp-web
  selector:
    app: {{ include "platformApiPoller.name" . }}
    release: {{ .Release.Name }}
    service: platform-api-poller
