apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: platformapi
spec:
  replicas: 1
  selector:
    matchLabels:
      service: platformapi
  template:
    metadata:
      labels:
        service: platformapi
    spec:
      containers:
      - name: platformapi
        image: gcr.io/light-reality-205619/platformapi-k8s:latest
        imagePullPolicy: Always
        env:
        - name: NP_K8S_API_URL
          value: http://localhost:8001
        - name: NP_K8S_AUTH_TYPE
          value: none
        - name: NP_STORAGE_TYPE
          value: nfs
        - name: NP_STORAGE_NFS_SERVER
          value: 10.128.0.5
        - name: NP_STORAGE_NFS_PATH
          value: /nfs
        - name: NP_STORAGE_HOST_MOUNT_PATH
          value: /nfs
        - name: NP_K8S_JOBS_INGRESS_NAME
          value: platformjobsingress
        - name: NP_K8S_JOBS_INGRESS_DOMAIN_NAME
          value: jobs.platform.dev.neuromation.io
      - name: kubeproxy
        image: lachlanevenson/k8s-kubectl:v1.10.3
        args: [proxy]
---
apiVersion: v1
kind: Service
metadata:
  name: platformapi
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    service: platformapi
