apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platformApi.fullname" . }}
  labels: {{ include "platformApi.labels.standard" . | nindent 4 }}
    service: platform-api
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "platformApi.name" . }}
      release: {{ .Release.Name }}
      service: platform-api
  {{- if .Values.strategy }}
  strategy: {{ toYaml .Values.strategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ include "platformApi.name" . }}
        release: {{ .Release.Name }}
        service: platform-api
      {{- if or .Values.annotations .Values.secrets }}
      annotations:
        {{- with .Values.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.secrets }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- end }}
      {{- end }}
    spec:
      containers:
      - name: platform-api
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        securityContext:
          {{- if .Values.securityContext.enabled }}
          runAsUser: {{ .Values.securityContext.runAsUser }}
          runAsGroup: {{ .Values.securityContext.runAsGroup }}
          runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          {{- end }}
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
{{- if .Values.resources }}
        resources: {{ toYaml .Values.resources | nindent 10 }}
{{- end }}
        env:
        - name: NP_AUTH_URL
          value: {{ .Values.platform.authUrl | quote }}
        - name: NP_AUTH_TOKEN
{{- if .Values.platform.token }}
{{ toYaml .Values.platform.token | indent 10 }}
{{- end }}
        - name: NP_OAUTH_AUTH_URL
          value: {{ .Values.oauth.authUrl | quote }}
        - name: NP_OAUTH_TOKEN_URL
          value: {{ .Values.oauth.tokenUrl | quote }}
        - name: NP_OAUTH_LOGOUT_URL
          value: {{ .Values.oauth.logoutUrl | quote }}
        - name: NP_OAUTH_CLIENT_ID
          value: {{ .Values.oauth.clientId | quote }}
        - name: NP_OAUTH_AUDIENCE
          value: {{ .Values.oauth.audience | quote }}
        - name: NP_OAUTH_SUCCESS_REDIRECT_URL
          value: {{ .Values.oauth.successRedirectUrl | quote }}
        - name: NP_OAUTH_HEADLESS_CALLBACK_URL
          value: {{ .Values.oauth.headlessCallbackUrl | quote }}
        - name: NP_API_URL
          value: {{ .Values.platform.apiPublicUrl | quote }}
        - name: NP_ADMIN_URL
          value: {{ .Values.platform.adminUrl | quote }}
        - name: NP_ADMIN_PUBLIC_URL
          value: {{ .Values.platform.adminPublicUrl | quote }}
        - name: NP_AUTH_PUBLIC_URL
          value: {{ .Values.platform.authPublicUrl | quote }}
        - name: NP_PLATFORM_CONFIG_URI
          value: {{ .Values.platform.configUrl | quote }}
        - name: NP_NOTIFICATIONS_URL
          value: {{ .Values.platform.notificationsUrl | quote }}
        - name: NP_NOTIFICATIONS_TOKEN
{{- if .Values.platform.token }}
{{ toYaml .Values.platform.token | indent 10 }}
{{- end }}
        - name: NP_ENFORCER_PLATFORM_API_URL
          value: http://localhost:8080/api/v1
        - name: NP_ENFORCER_RETENTION_DELAY_DAYS
          value: {{ .Values.enforcerRetentionDelayDays | quote }}
        - name: NP_DB_POSTGRES_DSN
{{- if .Values.postgres.dsn }}
{{ toYaml .Values.postgres.dsn | indent 10 }}
{{- end }}
        {{- if .Values.sentry }}
        - name: SENTRY_DSN
          value: {{ .Values.sentry.dsn }}
        - name: SENTRY_CLUSTER_NAME
          value: {{ .Values.sentry.clusterName }}
        - name: SENTRY_APP_NAME
          value: platform-api
        - name: SENTRY_SAMPLE_RATE
          value: {{ .Values.sentry.sampleRate | default 0 | quote }}
        {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
