
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "platformApi.fullname" . }}
  labels:
    {{- include "platformApi.labels.standard" . | nindent 4 }}
    platform.apolo.us/ping: "true"
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    platform.apolo.us/ping-url: https://{{ .Values.ingress.hosts | first }}/api/v1/ping/jobs
    {{- if .Capabilities.APIVersions.Has "traefik.io/v1alpha1" }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ include "platformApi.fullname" . }}-ping@kubernetescrd
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /api/v1
        pathType: Prefix
        backend:
          service:
            name: {{ include "platformApi.fullname" $ }}
            port:
              name: http
      - path: /api/v1/ping/jobs
        pathType: Prefix
        backend:
          service:
            name: {{ include "platformApi.fullname" $ }}
            port:
              name: http
  {{- end }}
{{- end }}
