
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "platformApi.fullname" . }}
  labels: {{ include "platformApi.labels.standard" . | nindent 4 }}
    service: platform-api
{{- with .Values.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4}}
{{- end }}
spec:
  rules:
{{- range .Values.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /api/v1
        backend:
          serviceName: {{ include "platformApi.fullname" $ }}
          servicePort: http
{{- end }}
{{- end }}
