
{{- if .Values.ingress.enabled }}
{{- $ingressApiIsStable := eq (include "k8s.ingress.isStable" .) "true" -}}
apiVersion: {{ include "k8s.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "platformApi.fullname" . }}
  labels: {{ include "platformApi.labels.standard" . | nindent 4 }}
    service: platform-api
  annotations:
    {{- if not $ingressApiIsStable }}
    kubernetes.io/ingress.class: traefik
    {{- end }}
    traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
    external-dns.platform.neuromation.io: "true"
spec:
  {{- if $ingressApiIsStable }}
  ingressClassName: traefik
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /api/v1
        {{- if $ingressApiIsStable }}
        pathType: Prefix
        {{- end }}
        backend:
          {{- if $ingressApiIsStable }}
          service:
            name: {{ include "platformApi.fullname" $ }}
            port:
              name: http
          {{- else }}
          serviceName: {{ include "platformApi.fullname" $ }}
          servicePort: http
          {{- end }}
  {{- end }}
{{- end }}
