# Only for dev environment.
# platform-operator is reposnsible for creating priority class
# bu it is not deployed in dev.
{{- if .Values.jobPriorityClass.enabled }}
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: platform-job
value: 1000000
globalDefault: false
{{- end }}
