apiVersion: v2
name: platform-api-poller
description: A Helm chart for platform-api-poller service
version: $CHART_VERSION
appVersion: $APP_VERSION
dependencies:
  - name: k8s-resources
    version: "1.0.1"
    repository: https://neuro-inc.github.io/helm-charts
