image:
  repository: "$IMAGE_REPO"
  tag: "$IMAGE_TAG"

imagePullSecrets: []

replicas: 1

securityContext:
  enabled: true
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  allowPrivilegeEscalation: false

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

platform:
  clusterName:
  authUrl:
  configUrl:
  adminUrl:
  apiUrl:
  registryUrl:
  registryEmail:
  token: {}

jobs:
  namespace: platform-jobs
  ingressClass: traefik
  ingressAuthMiddleware:
  ingressErrorPageMiddleware:
  tolerationKey: platform.neuromation.io/job
  preemptibleTolerationKey:
  imagePullSecret:

externalJobRunner:
  image:
    repository: ghcr.io/neuro-inc/externaljobrunner
    tag: latest

nodeLabels:
  job: platform.neuromation.io/job
  preemptible: platform.neuromation.io/preemptible
  nodePool: platform.neuromation.io/nodepool

resources:
  requests:
    cpu: "1"
    memory: "1Gi"

service:
  labels: {}
  annotations: {}

ingress:
  enabled: false

  ingressClassName: ""

  hosts: []

  labels: {}
  annotations: {}

secrets: []

sentry: {}

priorityClassName: ""
