platform:
  authUrl: http://platform-auth:8080
  configUrl: http://platform-config:8080/api/v1
  adminUrl: http://platform-admin:8080/apis/admin/v1
  apiUrl: http://platform-api:8080/api/v1
  registryUrl: https://registry-dev.neu.ro
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: compute_token

jobs:
  priorityClassName: platform-job
  ingressOAuthAuthorizeUrl: https://dev.neu.ro/oauth/authorize

storages:
- type: pvc
  claimName: pvc-platform-storage-jobs

ingress:
  enabled: true
  hosts: [dev.neu.ro]
  annotations:
    kubernetes.io/ingress.class: traefik
    external-dns.platform.neuromation.io: "true"
    # TODO: remove traefik v1 annotations
    traefik.frontend.rule.type: PathPrefix

sentry:
  dsn: https://432bc48cd2444be7afec5efeb1fc03a6@o489136.ingest.sentry.io/5530426
  clusterName: dev
  sampleRate: 0.002
