image:
  repository: "$IMAGE_REPO"
  tag: "$IMAGE_TAG"

imagePullSecrets: []

replicas: 1

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

platform:
  clusterName:
  authUrl:
  configUrl:
  adminUrl:
  apiUrl:
  registryUrl:
  registryEmail:
  token: {}

jobs:
  namespace: platform-jobs
  ingressClass: traefik
  ingressMiddleware:
  ingressOAuthAuthorizeUrl:
  tolerationKey: platform.neuromation.io/job
  preemptibleTolerationKey:
  priorityClassName:
  imagePullSecret:

nodeLabels:
  job: platform.neuromation.io/job
  gpu: platform.neuromation.io/accelerator
  preemptible: platform.neuromation.io/preemptible
  nodePool: platform.neuromation.io/nodepool

storages: []

resources:
  requests:
    cpu: "1"
    memory: "1Gi"

ingress:
  enabled: false
  # annotations:

secrets: []

zipkin: {}

sentry: {}
