resources:
  requests:
    cpu: "0.5"
    memory: "1Gi"

platform:
  clusterName: default
  authUrl: http://platform-auth:8080
  configUrl: http://platform-config:8080/api/v1
  adminUrl: http://platform-admin:8080/apis/admin/v1
  apiUrl: http://platform-api:8080/api/v1
  registryUrl: https://registry-dev.neu.ro
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: compute_token

jobs:
  ingressAuthMiddleware: platform-platform-ingress-auth@kubernetescrd
  ingressErrorPageMiddleware: platform-platform-web-ui-error-pages@kubernetescrd

storages:
- type: pvc
  claimName: platform-jobs-storage

ingress:
  enabled: true
  ingressClassName: traefik
  hosts: [dev.neu.ro]
  annotations:
    traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
    external-dns.platform.neuromation.io: "true"

sentry:
  dsn: https://432bc48cd2444be7afec5efeb1fc03a6@o489136.ingest.sentry.io/5530426
  clusterName: dev
  sampleRate: 0.002
