image:
  repository: "$IMAGE_REPO"
  tag: "$IMAGE_TAG"

imagePullSecrets: []

replicas: 1

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

platform:
  clusterName:
  authUrl:
  configUrl:
  adminUrl:
  apiUrl:
  registryUrl:
  registryEmail:
  token: {}

jobs:
  namespace: platform-jobs
  ingressClass: traefik
  ingressAuthMiddleware:
  ingressErrorPageMiddleware:
  tolerationKey: platform.neuromation.io/job
  preemptibleTolerationKey:
  imagePullSecret:

externalJobRunner:
  image:
    repository: ghcr.io/neuro-inc/externaljobrunner
    tag: latest

nodeLabels:
  job: platform.neuromation.io/job
  preemptible: platform.neuromation.io/preemptible
  nodePool: platform.neuromation.io/nodepool

storages: []

resources:
  requests:
    cpu: "1"
    memory: "1Gi"

ingress:
  enabled: false
  ingressClassName: ""
  hosts: []
  annotations: {}

secrets: []

externalSecrets: []
  # - name: platform-admin-secret
  #   secretStoreName: vault-backend
  #   secretStoreKind: ClusterSecretStore
  #   data:
  #     DATABASE_URL:
  #       key: kv-v2/platform
  #       property: DATABASE_URL
  #     API_KEY:
  #       key: kv-v2/platform
  #       property: API_KEY

sentry: {}

priorityClassName: ""
