apiVersion: v1
kind: Service
metadata:
  name: platformapi-poller{{ .Values.k8sSuffix }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: tcp-web
  selector:
    service: platformapi-poller{{ .Values.k8sSuffix }}
