IMAGE:
  _default: gcr.io/light-reality-205619/ssh-auth:latest
  dev: gcr.io/light-reality-205619/ssh-auth:latest
  staging: gcr.io/light-reality-205619/ssh-auth:latest
  prod: gcr.io/production-228907/ssh-auth:latest
NP_AUTH_URL:
  _default: http://platformauthapi:8080
  dev: http://platformauthapi:8080
  staging: http://platformauthapi:8080
  hse: http://platformauthapi:8080
NP_PLATFORM_API_URL:
  _default: http://platformapi:8080/api/v1
  dev: http://platformapi:8080/api/v1
  staging: http://platformapi:8080/api/v1
  hse: http://platformapi:8080/api/v1
NP_K8S_NS:
  _default: default
  dev: default
  staging: default
  hse: default
