apiVersion: v2
name: platform-api
description: A Helm chart for platform-api service
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: k8s-resources
    version: "1.0.1"
    repository: https://neuro-inc.github.io/helm-charts
  - name: postgres-db-init
    version: "1.2.18"
    repository: https://neuro-inc.github.io/helm-charts
