apiVersion: v2
name: platform-api
description: A Helm chart for platform-api service
version: 1.1.0
appVersion: 1.0.0
dependencies:
  - name: postgres-db-init
    version: "1.2.19"
    repository: https://neuro-inc.github.io/helm-charts
