platform:
  apiPublicUrl: https://staging.neu.ro/api/v1
  adminPublicUrl: https://staging.neu.ro/apis/admin/v1
  authPublicUrl: https://staging.neu.ro/api/v1/users
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: compute_token

oauth:
  authUrl: https://login.neu.ro/authorize
  tokenUrl: https://login.neu.ro/oauth/token
  logoutUrl: https://login.neu.ro/v2/logout?returnTo=https://app.neu.ro/cli-logout
  clientId: uJV0pm5JPdHkXsSd525rlhFDVcEuUnaV
  audience: https://platform.staging.neuromation.io
  successRedirectUrl: https://staging.neu.ro/oauth/login
  headlessCallbackUrl: https://staging.neu.ro/oauth/show-code

cors:
  origins:
  - https://neu.ro
  - https://release--neuro-web.netlify.com
  - https://app.neu.ro
  - https://mts.neu.ro

postgres:
  dsn:
    valueFrom:
      secretKeyRef:
        name: platformapi-postgres
        key: platformapi-service-dsn

postgres-db-init:
  adminDsn:
    valueFrom:
      secretKeyRef:
        name: postgres
        key: admin-dsn
  migrationsRunnerDsn:
    valueFrom:
      secretKeyRef:
        name: platformapi-postgres
        key: platformapi-migrations-dsn
  serviceDsn:
    valueFrom:
      secretKeyRef:
        name: platformapi-postgres
        key: platformapi-service-dsn

  migrations:
    env:
      - name: NP_DB_POSTGRES_DSN
        valueFrom:
          secretKeyRef:
            name: platformapi-postgres
            key: platformapi-migrations-dsn

ingress:
  enabled: true

  extraAnnotations:
    external-dns.platform.neuromation.io: "true"
  hosts: [staging.neu.ro]

sentry:
  dsn: https://80b17e5f9cae4243a4a8b791e6481c9a@o489136.ingest.sentry.io/5553359
  clusterName: staging
  sampleRate: 0.002
