platform:
  apiPublicUrl: https://ml.cloud.mts.ru/api/v1
  adminPublicUrl: https://ml.cloud.mts.ru/apis/admin/v1
  authPublicUrl: https://ml.cloud.mts.ru/api/v1/users
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: compute_token

oauth:
  authUrl: https://login.ml.cloud.mts.ru/auth/realms/neu.ro/protocol/openid-connect/auth
  tokenUrl: https://login.ml.cloud.mts.ru/auth/realms/neu.ro/protocol/openid-connect/token
  logoutUrl: https://login.ml.cloud.mts.ru/auth/realms/neu.ro/protocol/openid-connect/logout
  clientId: neuro-client
  audience: https://platform.ml.cloud.mts.ru
  successRedirectUrl: https://ml.cloud.mts.ru/oauth/login
  headlessCallbackUrl: https://ml.cloud.mts.ru/oauth/show-code

cors:
  origins:
  - https://ml.cloud.mts.ru
  - https://app.ml.cloud.mts.ru

postgres:
  dsn:
    valueFrom:
      secretKeyRef:
        name: platformapi-postgres
        key: platformapi-service-dsn

postgres-db-init:
  adminDsn:
    valueFrom:
      secretKeyRef:
        name: postgres
        key: admin-dsn
  migrationsRunnerDsn:
    valueFrom:
      secretKeyRef:
        name: platformapi-postgres
        key: platformapi-migrations-dsn
  serviceDsn:
    valueFrom:
      secretKeyRef:
        name: platformapi-postgres
        key: platformapi-service-dsn

  migrations:
    env:
      - name: NP_DB_POSTGRES_DSN
        valueFrom:
          secretKeyRef:
            name: platformapi-postgres
            key: platformapi-migrations-dsn


ingress:
  enabled: true

  hosts: [ml.cloud.mts.ru]
