resources:
  requests:
    cpu: "0.5"
    memory: "1Gi"

enforcerRetentionDelayDays: 30

platform:
  apiPublicUrl: https://dev.neu.ro/api/v1
  adminPublicUrl: https://dev.neu.ro/apis/admin/v1
  authPublicUrl: https://dev.neu.ro/api/v1/users
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: compute_token

oauth:
  authUrl: https://login-dev.neu.ro/authorize
  tokenUrl: https://login-dev.neu.ro/oauth/token
  logoutUrl: https://login-dev.neu.ro/v2/logout?returnTo=https://master--neuro-web.netlify.app/cli-logout
  clientId: V7Jz87W9lhIlo0MyD0O6dufBvcXwM4DR
  audience: https://platform.dev.neuromation.io
  successRedirectUrl: https://dev.neu.ro/oauth/login
  headlessCallbackUrl: https://dev.neu.ro/oauth/show-code


cors:
  origins:
  - '*'

postgres:
  dsn:
    valueFrom:
      secretKeyRef:
        name: platform-api-postgres
        key: service-dsn

postgres-db-init:
  adminDsn:
    valueFrom:
      secretKeyRef:
        name: platform-postgresql
        key: postgresql-dsn
  migrationsRunnerDsn:
    valueFrom:
      secretKeyRef:
        name: platform-api-postgres
        key: migrations-dsn
  serviceDsn:
    valueFrom:
      secretKeyRef:
        name: platform-api-postgres
        key: service-dsn
  migrations:
    env:
      - name: NP_DB_POSTGRES_DSN
        valueFrom:
          secretKeyRef:
            name: platform-api-postgres
            key: migrations-dsn

ingress:
  enabled: true
  hosts: [dev.neu.ro]

sentry:
  dsn: https://432bc48cd2444be7afec5efeb1fc03a6@o489136.ingest.sentry.io/5530426
  clusterName: dev
  sampleRate: 0.002
