IMAGE:
  _default: gcr.io/light-reality-205619/platformapi-k8s:latest
  dev: gcr.io/light-reality-205619/platformapi-k8s:latest
  staging: gcr.io/light-reality-205619/platformapi-k8s:latest
  prod: gcr.io/production-228907/platformapi-k8s:latest
INGRESS_FALLBACK_IMAGE:
  _default: gcr.io/light-reality-205619/platformingressfallback:latest
  dev: gcr.io/light-reality-205619/platformingressfallback:latest
  staging: gcr.io/light-reality-205619/platformingressfallback:latest
  prod: gcr.io/production-228907/platformingressfallback:latest
NP_STORAGE_NFS_SERVER:
  _default: '10.76.126.154'
  dev: '10.76.126.154'
  staging: '10.69.59.50'
  prod: '10.47.20.74'
NP_STORAGE_NFS_PATH:
  _default: '/dev2premium'
  dev: '/dev2premium'
  staging: '/devpremium'
  prod: '/prodpremium'
NP_K8S_JOBS_INGRESS_DOMAIN_NAME_TEMPLATE:
  _default: '{job_id}.jobs-dev.neu.ro'
  dev: '{job_id}.jobs-dev.neu.ro'
  staging: '{job_id}.jobs-staging.neu.ro'
  prod: '{job_id}.jobs.neu.ro'
NP_K8S_NAMED_JOBS_INGRESS_DOMAIN_NAME_TEMPLATE:
  _default: '{job_name}-{job_owner}.jobs-dev.neu.ro'
  dev: '{job_name}-{job_owner}.jobs-dev.neu.ro'
  staging: '{job_name}-{job_owner}.jobs-staging.neu.ro'
  prod: '{job_name}-{job_owner}.jobs.neu.ro'
NP_K8S_SSH_AUTH_INGRESS_DOMAIN_NAME:
  _default: ssh-auth-dev.neu.ro
  dev: ssh-auth-dev.neu.ro
  staging: ssh-auth-staging.neu.ro
  prod: ssh-auth.neu.ro
NP_API_URL:
  _default: https://dev.neu.ro/api/v1
  dev: https://dev.neu.ro/api/v1
  staging: https://staging.neu.ro/api/v1
  prod: https://neu.ro/api/v1
INGRESS_HOST:
  _default: platform.dev.neuromation.io
  dev: platform.dev.neuromation.io
  staging: platform.staging.neuromation.io
  prod: platform.prod.neuromation.io
INGRESS_HOST_TEMPORARY:
  _default: dev.ai.neuromation.io
  dev: dev.ai.neuromation.io
  staging: staging.ai.neuromation.io
  prod: ai.neuromation.io
INGRESS_HOST_TEMPORARY_NEW_DOMAIN:
  _default: dev.neu.ro
  dev: dev.neu.ro
  staging: staging.neu.ro
  prod: neu.ro
INGRESS_MAIN_SITE_HOST:
  _default: neu.ro
  dev:
  staging: neu.ro
  prod:
INGRESS_FALLBACK_HOST:
  _default: 'default.jobs-dev.neu.ro'
  dev: 'default.jobs-dev.neu.ro'
  staging: 'default.jobs-staging.neu.ro'
  prod: 'default.jobs.neu.ro'
NP_DB_REDIS_URI:
  _default: redis://10.0.0.11:6379/0
  dev: redis://10.0.0.11:6379/0
  staging: redis://10.0.0.3:6379/1
  prod: redis://10.0.0.3:6379/0
NP_REGISTRY_HOST:
  _default: registry-dev.neu.ro
  dev: registry-dev.neu.ro
  staging: registry-staging.neu.ro
  prod: registry.neu.ro
NP_GKE_GPU_MODELS:
  _default: nvidia-tesla-k80,nvidia-tesla-p4,nvidia-tesla-v100
  dev: nvidia-tesla-k80,nvidia-tesla-p4,nvidia-tesla-v100
  staging: nvidia-tesla-k80,nvidia-tesla-p4,nvidia-tesla-v100
  prod: nvidia-tesla-k80,nvidia-tesla-p4,nvidia-tesla-v100
NP_OAUTH_BASE_URL:
  _default: https://dev-neuromation.auth0.com
  dev: https://dev-neuromation.auth0.com
  staging: https://staging-neuromation.auth0.com
  prod:
NP_OAUTH_CLIENT_ID:
  _default: V7Jz87W9lhIlo0MyD0O6dufBvcXwM4DR
  dev: V7Jz87W9lhIlo0MyD0O6dufBvcXwM4DR
  staging: uJV0pm5JPdHkXsSd525rlhFDVcEuUnaV
  prod:
NP_OAUTH_AUDIENCE:
  _default: https://platform.dev.neuromation.io
  dev: https://platform.dev.neuromation.io
  staging: https://platform.staging.neuromation.io
  prod: https://platform.prod.neuromation.io
NP_OAUTH_SUCCESS_REDIRECT_URL:
  _default: https://neu.ro/#running-your-first-job
  dev: https://neu.ro/#running-your-first-job
  staging: https://neu.ro/#running-your-first-job
  prod: https://neu.ro/#running-your-first-job
NP_OAUTH_HEADLESS_CALLBACK_URL:
  _default: https://staging.neu.ro/oauth/show-code
  dev: https://dev.neu.ro/oauth/show-code
  staging: https://staging.neu.ro/oauth/show-code
  prod: https://prod.neu.ro/oauth/show-code
