NP_API_URL: https://dev.neu.ro/api/v1
NP_ADMIN_URL: https://dev.neu.ro/apis/admin/v1
NP_AUTH_PUBLIC_URL: https://dev.neu.ro/api/v1/users
NP_REGISTRY_HOST: registry-dev.neu.ro
NP_GKE_GPU_MODELS: nvidia-tesla-k80,nvidia-tesla-p4,nvidia-tesla-v100
NP_OAUTH_AUTH_URL: https://login-dev.neu.ro/authorize
NP_OAUTH_TOKEN_URL: https://login-dev.neu.ro/oauth/token
NP_OAUTH_LOGOUT_URL: https://login-dev.neu.ro/v2/logout&returnTo=https://master--neuro-web.netlify.app/cli-logout
NP_OAUTH_CLIENT_ID: V7Jz87W9lhIlo0MyD0O6dufBvcXwM4DR
NP_OAUTH_AUDIENCE: https://platform.dev.neuromation.io
NP_OAUTH_SUCCESS_REDIRECT_URL: https://dev.neu.ro/oauth/login
NP_OAUTH_HEADLESS_CALLBACK_URL: https://dev.neu.ro/oauth/show-code
NP_CORS_ORIGINS: https://neu.ro,https://master--neuro-web.netlify.app,http://localhost:8000,https://master--mts-web.netlify.app,https://master--megafon-web.netlify.app,https://master--minzdav-web.netlify.app
NP_SENTRY_URL: "https://11316dd021994d7085c50e86c2ae404c@o454648.ingest.sentry.io/5597106"
NP_SENTRY_CLUSTER_NAME: "dev-gcp"
NP_SENTRY_SAMPLE_RATE: 0.1

platform:
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: compute_token

jobPriorityClass:
  enabled: true

postgres:
  dsn:
    valueFrom:
      secretKeyRef:
        name: platformapi-postgres
        key: platformapi-service-dsn

postgres-db-init:
  adminDsn:
    valueFrom:
      secretKeyRef:
        name: postgres
        key: admin-dsn
  migrationsRunnerDsn:
    valueFrom:
      secretKeyRef:
        name: platformapi-postgres
        key: platformapi-migrations-dsn
  serviceDsn:
    valueFrom:
      secretKeyRef:
        name: platformapi-postgres
        key: platformapi-service-dsn

  migrations:
    env:
      - name: NP_DB_POSTGRES_DSN
        valueFrom:
          secretKeyRef:
            name: platformapi-postgres
            key: platformapi-migrations-dsn

ingress:
  enabled: true

  extraAnnotations:
    external-dns.platform.neuromation.io: "true"
  hosts: [dev.neu.ro]
