IMAGE:
  _default: gcr.io/light-reality-205619/platformapi-k8s:latest
  dev: gcr.io/light-reality-205619/platformapi-k8s:latest
  staging: gcr.io/light-reality-205619/platformapi-k8s:latest
NP_STORAGE_NFS_SERVER:
  _default: '10.128.0.5'
  dev: '10.128.0.5'
  staging: '10.128.0.14'
NP_K8S_JOBS_INGRESS_DOMAIN_NAME:
  _default: jobs.platform.dev.neuromation.io
  dev: jobs.platform.dev.neuromation.io
  staging: jobs.platform.staging.neuromation.io
INGRESS_HOST:
  _default: platform.dev.neuromation.io
  dev: platform.dev.neuromation.io
  staging: platform.staging.neuromation.io
NP_DB_REDIS_URI:
  _default: redis://10.0.0.3:6379/0
  dev: redis://10.0.0.3:6379/0
  staging: redis://10.0.0.3:6379/1
NP_REGISTRY_HOST:
  _default: registry.dev.neuromation.io
  dev: registry.dev.neuromation.io
  staging: registry.staging.neuromation.io
