IMAGE:
  _default: gcr.io/light-reality-205619/platformapi-k8s:latest
  dev: gcr.io/light-reality-205619/platformapi-k8s:latest
  staging: gcr.io/light-reality-205619/platformapi-k8s:latest
NP_STORAGE_NFS_SERVER:
  _default: '172.27.83.58'
  dev: '172.27.83.58'
  staging: '10.69.59.50'
NP_STORAGE_NFS_PATH:
  _default: '/staging_premium'
  dev: '/staging_premium'
  staging: '/devpremium'
NP_K8S_JOBS_INGRESS_DOMAIN_NAME:
  _default: jobs.platform.dev.neuromation.io
  dev: jobs.platform.dev.neuromation.io
  staging: jobs.platform.staging.neuromation.io
NP_K8S_SSH_INGRESS_DOMAIN_NAME:
  _default: ssh.platform.dev.neuromation.io
  dev: ssh.platform.dev.neuromation.io
  staging: ssh.platform.staging.neuromation.io
INGRESS_HOST:
  _default: platform.dev.neuromation.io
  dev: platform.dev.neuromation.io
  staging: platform.staging.neuromation.io
NP_DB_REDIS_URI:
  _default: redis://10.0.0.3:6379/0
  dev: redis://10.0.0.3:6379/0
  staging: redis://10.0.0.3:6379/1
NP_REGISTRY_HOST:
  _default: registry.dev.neuromation.io
  dev: registry.dev.neuromation.io
  staging: registry.staging.neuromation.io
NP_GKE_GPU_MODELS:
  _default: nvidia-tesla-k80,nvidia-tesla-p4,nvidia-tesla-v100
  dev: nvidia-tesla-k80,nvidia-tesla-p4,nvidia-tesla-v100
  staging: nvidia-tesla-k80,nvidia-tesla-p4,nvidia-tesla-v100
NP_REQUESTS_CPU:
  _default: "0.2"
  dev: "0.2"
  staging: "0.2"
NP_LIMITS_CPU:
  _default: "1"
  dev: "0.5"
  staging: "0.5"
NP_REQUESTS_MEMORY:
  _default: "300Mi"
  dev: "200Mi"
  staging: "100Mi"
NP_LIMITS_MEMORY:
  _default: "2Gi"
  dev: "1Gi"
  staging: "500Mi"
NP_REPLICAS:
  _default: "2"
  dev: "2"
  staging: "2"
