name: Release

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

permissions:
  contents: write
  packages: write

jobs:
  publish_image:
    name: Publish Image
    runs-on: ubuntu-latest
    concurrency: release_image
    outputs:
      tag: ${{ steps.release.outputs.tag }}
      version: ${{ steps.release.outputs.version }}
      skip: ${{ steps.release.outputs.skip }}
    steps:
    - name: Purge old artifacts
      uses: kolpav/purge-artifacts-action@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        expire-in: 30mins
    - name: Release image
      id: release
      uses: neuro-inc/release-image-action@v21.9.36
      with:
        image: platformapi
        token: ${{ secrets.GH_TOKEN }}
    - name: Checkout commit
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_sha }}
        fetch-depth: 0
    - name: Github Release
      if: ${{ ! steps.release.outputs.skip }}
      run: |
        if [[ -n $PRERELEASE ]]; then
          gh release create "$TAG" --prerelease --notes "docker pull ghcr.io/neuro-inc/platformapi:$VERSION"
        else
          gh release create "$TAG" --notes "docker pull ghcr.io/neuro-inc/platformapi:$VERSION"
        fi
      shell: bash
      env:
        TAG: ${{ steps.release.outputs.tag }}
        VERSION: ${{ steps.release.outputs.version }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        PRERELEASE: ${{ steps.release.outputs.prerelease }}
  publish_chart:
    name: Publish Helm chart
    runs-on: ubuntu-latest
    needs: publish_image
    if: ${{ ! needs.publish_image.outputs.skip }}
    concurrency: release_helm_chart
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_sha }}
        fetch-depth: 0
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.7.0
    - name: Create platform-api chart
      run: make helm_create_chart
      env:
        IMAGE_REGISTRY: github
        TAG: ${{ needs.publish_image.outputs.tag }}
        GITHUB_OWNER: ${{ github.repository_owner }}
        HELM_CHART: platform-api
        HELM_CHART_VERSION: ${{ needs.publish_image.outputs.version }}
        HELM_APP_VERSION: ${{ needs.publish_image.outputs.version }}
    - name: Create platform-api-poller chart
      run: make helm_create_chart
      env:
        IMAGE_REGISTRY: github
        TAG: ${{ needs.publish_image.outputs.tag }}
        GITHUB_OWNER: ${{ github.repository_owner }}
        HELM_CHART: platform-api-poller
        HELM_CHART_VERSION: ${{ needs.publish_image.outputs.version }}
        HELM_APP_VERSION: ${{ needs.publish_image.outputs.version }}
    - name: Release charts
      uses: helm/chart-releaser-action@v1.2.1
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
